"""conftest.py — wires qaplay to this system's login.

Generated by /ipassion-qa-automation:qa-init. Edit `login` to match your app.

qaplay's fixtures (`step`, `page_as`, `browser`, ...) are async, so this
project's own pytest config must set all three of:

    [tool.pytest.ini_options]
    asyncio_mode = "auto"
    asyncio_default_fixture_loop_scope = "session"
    asyncio_default_test_loop_scope = "session"

(pyproject.toml, or the equivalent [pytest] section in pytest.ini/setup.cfg —
qa-init writes these) — the plugin does not set this for its own host
project. `browser` below is session-scoped (launch chromium once, not per
test), and pytest-asyncio binds each async fixture/test to the event loop of
its own scope: a session-scoped fixture on a *different* loop than a
function-scoped test hangs the first `await` that crosses between them (e.g.
`browser.new_context()` never returns) — pinning both fixture and test loop
scope to "session" keeps them on the one loop `browser` was created on.
"""
import json
import os
import sys
from pathlib import Path

import pytest
from playwright.async_api import async_playwright

# Claude Code ตั้ง CLAUDE_PLUGIN_ROOT ให้เอง · ตอนรัน pytest เองจากเทอร์มินัล
# ไม่มีตัวแปรนี้ ถ้าอ่านตรง ๆ จะ KeyError ตั้งแต่ collect · fallback ไปที่
# โฟลเดอร์ qa-plugin/ ในรากโปรเจกต์ถ้ามี
PLUGIN = Path(os.environ.get("CLAUDE_PLUGIN_ROOT")
              or Path(__file__).resolve().parent / "qa-plugin")
sys.path.insert(0, str(PLUGIN))

# This module's own root (holds pages/, components/, flows/) — needed so
# `from pages.login_page import LoginPage` etc. resolve regardless of which
# directory pytest happened to pick as its import-mode basedir.
MODULE_ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(MODULE_ROOT))

pytest_plugins = ["engine.qaplay.plugin"]

from engine.qaplay import auth  # noqa: E402
from engine import config as cfg  # noqa: E402
from engine.qaplay.browser import (BrowserOpenError, close_browser,
                                   open_browser)  # noqa: E402
from engine.qaplay.nav import goto_with_retry  # noqa: E402

from pages.login_page import LoginPage  # noqa: E402


@pytest.fixture(scope="session", autouse=True)
def qa_env(qa_config, qa_doc):
    """environment ของรอบรัน — **เอกสาร testcase บอกเอง** (``meta.env``)

    registry อยู่ที่ ``module.json.environments`` · ผลถูกวางไว้ที่
    ``conf["base_url"]`` ให้ ``page_as`` และโค้ดของระบบอ่านต่อ จึงไม่มีใครต้อง
    ตั้งตัวแปรก่อนรัน · ``QA_BASE_URL`` ยังทับได้ แต่ resolve_env จะเตือนดัง
    """
    conf, _ = qa_config
    env = cfg.resolve_env(conf, qa_doc.get("meta"))
    conf["base_url"] = env.base_url
    print(f"\n[env] {env.name} ({env.label}) → {env.base_url}  [source={env.source}]")
    return env


@pytest.fixture(scope="session")
async def browser(qa_config):
    """browser ของรอบรัน — `qa.config.json` คีย์ `browser` บอกว่าจะใช้ตัวไหน

    `engine.qaplay.browser.open_browser` รองรับสองโหมด: `launch` (Playwright
    เปิดเอง · เลือก channel / executable_path / user_data_dir ได้) และ `cdp`
    (ไปเกาะ browser ที่เปิดค้างไว้ผ่าน remote-debugging-port — ใช้เมื่อ network
    stack ของเครื่องที่รันเชื่อถือไม่ได้ เช่น WSL2 mirrored ที่ตัด request
    ทิ้งเวลา adapter ฝั่ง Windows ขยับ) · ดู docstring ของโมดูลนั้น
    """
    conf, _ = qa_config
    async with async_playwright() as pw:
        try:
            b, target = await open_browser(pw, conf)
        except (BrowserOpenError, cfg.BrowserError) as exc:
            pytest.exit(f"เปิด browser ไม่ได้: {exc}", returncode=1)
        yield b
        # โหมด cdp ต้องไม่ปิด browser ที่เกาะอยู่ — close_browser รู้เอง
        await close_browser(b, target)


def _module_base_url() -> str:
    """The app's dev-server URL, read straight from module.json.

    `login()` runs during session minting (engine.qaplay.auth.ensure_state),
    before any TC/qa_doc context exists, so it cannot rely on the qa_env
    fixture's meta.env-based resolution — it needs a URL to `page.goto()`
    before anything else. This app defines no named `environments` in
    module.json (single dev-server target), so reading `base_url` directly
    is exactly what engine.config.resolve_env would fall back to anyway.
    """
    data = json.loads((MODULE_ROOT / "module.json").read_text(encoding="utf-8"))
    return data["base_url"]


async def login(page, role):
    """Drive this system's login screen for `role`.

    This app has no server-side redirect and nothing to settle beyond the
    sign-in itself (no profile picker, no tenant selector) — see
    sys_summary.md §1/§7.

    'admin' uses the one-click card. 'readonly' is a demo-mode-only account
    (registry/demoStore.ts's demoReadOnly) added specifically so TRAIN-0006
    (admin-gated writes) can be exercised without a real Supabase Auth user —
    sys_summary.md §7 still holds for a Supabase-backed environment: no
    non-admin account is provisioned there, so this branch will fail loud
    against anything but demo mode until one is created and its credentials
    are added to `.env.qa` in place of the demo defaults below.
    """
    await page.goto(_module_base_url(), wait_until="domcontentloaded")
    login_page = LoginPage(page)
    if role == "admin":
        await login_page.sign_in_as_admin()
    elif role == "readonly":
        email = cfg.resolve_value("$QA_READONLY_EMAIL")
        password = cfg.resolve_value("$QA_READONLY_PASSWORD")
        await login_page.sign_in_manual(email, password)
    else:
        raise NotImplementedError(f"login(): no credentials wired up for role={role!r}")
    # Hand back a page that has actually reached the authenticated shell —
    # not just one that clicked the button — so a caller relying on
    # storage_state captured right after this never gets a half-signed-in
    # session frozen into the cache.
    await page.get_by_role("button", name="Overview", exact=True).wait_for()


async def _on_login_screen(page) -> bool:
    """Is `page` currently showing the (unauthenticated) login screen?

    This app has **no distinct login URL** (sys_summary.md §2 — no
    client-side router; the login screen and every authenticated screen
    share the exact same address), so the qaplay template's URL-substring
    dead-session check cannot work here by construction — any marker string
    chosen would either never match (missing real expiry) or always match
    (false-positive on every fresh navigation). This DOM check replaces it:
    the admin one-click card only renders when `session === null`.
    """
    return await LoginPage(page).is_showing()


@pytest.fixture
async def page_as(browser, qa_config, qa_workspace, step, tc):
    conf, _ = qa_config
    ttl = float(conf.get("session_ttl_minutes", 15))
    # A page opened at a viewport Playwright's own default (1280x720) picked
    # rather than the TC's own declared size is not testing what the TC says
    # it is testing — a layout that collapses its nav at an unintended width
    # can resolve a menu to a non-actionable element, which reads as an
    # unrelated selector bug. Resolve the TC's own "viewport" field
    # ("desktop"/"mobile"/...) via engine.config.viewports() instead of
    # letting new_context() fall back to Playwright's default silently.
    viewport_name = tc.data.get("viewport", "desktop")
    all_viewports = cfg.viewports(conf)
    viewport = all_viewports.get(viewport_name) or all_viewports["desktop"]

    async def _open(role: str, url: str | None = None):
        # A page built from a saved storage_state (browser.new_context(
        # storage_state=...) + new_page()) has never been navigated anywhere
        # — it is about:blank. A caller that doesn't pass `url` must not get
        # that blank page back verbatim: nothing could redirect *from* it, so
        # the expiry check below would never run. Fall back to qa_config's
        # own base_url (qa_env sets it from the document's meta.env), and fail
        # loud (not a silent about:blank) if there isn't one to fall back to.
        url = url or conf.get("base_url")
        if not url:
            raise ValueError(
                "page_as() needs a url, and qa_config has no 'base_url' to "
                "fall back to (check qa.config.json / module.json)"
            )

        # This app has no login URL to ask for (see _on_login_screen's
        # docstring) — page_as() always means "give me an authenticated
        # page", never "take me to the login screen on purpose". A caller
        # that genuinely wants the raw, unauthenticated login screen should
        # open its own context/page directly (as tests/smoke/test_flows.py
        # does) rather than go through this fixture.
        page = await _fresh_page(role, force=False)
        await goto_with_retry(page, url, wait_until="domcontentloaded")

        if await _on_login_screen(page):
            # the cached state was dead on the server — mint once and retry
            await page.context.close()
            page = await _fresh_page(role, force=True)
            await goto_with_retry(page, url, wait_until="domcontentloaded")
            if await _on_login_screen(page):
                # still on login after a fresh mint: not a stale cache
                # anymore — login() itself isn't working, or this account
                # can't reach `url`. Fail loud here instead of handing
                # back a login-screen page that later fails as a
                # confusing "element not found".
                raise RuntimeError(
                    f"still on the login screen after re-authenticating "
                    f"as {role!r} (url={page.url}) — login() is not "
                    f"working, or this account cannot reach {url}"
                )
        return step.attach(page)

    async def _fresh_page(role: str, *, force: bool):
        state = await auth.ensure_state(browser, qa_workspace, role,
                                        login=login, ttl_minutes=ttl, force=force)
        ctx = await browser.new_context(storage_state=str(state), viewport=viewport)
        return await ctx.new_page()

    return _open
